---
# 文档元数据
metadata:
  title: "The Rust Programming Language"
  authors:
    - "by Steve Klabnik and Carol Nichols, with contributions from the Rust Community"
  author_prefix: ""
  language: "en-US"
  rights: "CC BY-NC-SA 4.0"
  keywords: "Rust,Systems Programming,Programming"
  subject: "The Rust Programming Language Guide"
  creator: "LaTeX with hyperref"
  producer: "xelatex"

# PDF 输出设置
pdf:
  engine: xelatex
  template: templates/latex/main.tex
  options:
    - --pdf-engine=xelatex
    - --standalone
    - --top-level-division=chapter

# 目录设置
toc:
  depth: 3
  title: "目录"

# 页面设置
page:
  size: a4
  margins:
    top: 2.5cm
    bottom: 2.5cm
    left: 2.5cm
    right: 2.5cm

# 字体设置
fonts:
  main: SimSun
  sans: SimHei
  mono: SimFang
  size: 12pt
  
# 处理设置
processing:
  clean: true
  standalone: true
  number-sections: true
  pdf-engine: xelatex
  top-level-division: chapter
--- 